---
  language: go
  sudo: false
  notifications:
    email: false
  go:
    - 1.6
    - tip
  script:
    - test -z "$(gofmt -s -l . | grep -v vendor/ | tee /dev/stderr)"
    - go list ./... | go test -v
